version: '3.8'

services:
  api:
    build: ./backend
    container_name: devilfruit_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app
      - sqlite_data:/app/data  # This uses a named volume for persistence
    ports:
      - "8000:8000"

  web:
    build: ./frontend
    container_name: devilfruit_web
    command: bun run dev --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api

volumes:
  # This defines the named volume that Docker will manage
  sqlite_data: