services:
  db-populate:
    build: 
      context: .
      target: dev
    command: python -m app.core.db_management force-reset --env ${ENVIRONMENT} --upload
    volumes:
      - ./app:/app
      - sqlite-db-data:/app/data/db:rw
      - ./app/data/backups:/app/data/backups
      - ${GOOGLE_APPLICATION_CREDENTIALS_LOCAL}:${GOOGLE_APPLICATION_CREDENTIALS}:ro
    env_file:
      - .env
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - PYTHONPATH=../
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    profiles:
      - populate

  backend:
    build: 
      context: .
      target: dev
    restart: no
    container_name: devil-fruit-backend
    volumes:
      - ./app:/app
      - sqlite-db-data:/app/data/db
      - ./app/data/backups:/app/data/backups
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - ENVIRONMENT=${ENVIRONMENT}
      - PYTHONPATH=../
    ports:
      - 8000:8000
  
volumes:
  sqlite-db-data:
    name: devil-fruit-sqlite-data
    driver: local