name: "Build and Deploy"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  pages: write
  packages: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - id: "auth"
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.4
        with:
          project_id: devil-fruit-database-id
          create_credentials_file: true
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_POOL_ID }}/providers/${{ secrets.GCP_PROVIDER_ID }}"
          service_account: "devil-fruit-database-gsa@devil-fruit-database-id.iam.gserviceaccount.com"

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        working-directory: ./frontend

      - name: Build frontend
        run: bun run build
        working-directory: ./frontend

      - name: Upload frontend build artifacts
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: frontend-dist
          path: ./frontend/dist

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tag
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "DOCKER_TAG=ghcr.io/${{ github.repository_owner }}/devil-fruit-backend:pr-${{ github.event.number }}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=ghcr.io/${{ github.repository_owner }}/devil-fruit-backend:latest" >> $GITHUB_ENV
          fi

      - name: Build docker image
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./backend
          push: false
          tags: ${{ env.DOCKER_TAG }}

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - id: "auth"
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.4
        with:
          project_id: devil-fruit-database-id
          create_credentials_file: true
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_POOL_ID }}/providers/${{ secrets.GCP_PROVIDER_ID }}"
          service_account: "devil-fruit-database-gsa@devil-fruit-database-id.iam.gserviceaccount.com"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: "latest"

      - name: Download frontend build artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          name: frontend-dist
          path: ./frontend/dist

      - name: Deploy frontend
        uses: actions/deploy-pages@v4.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: frontend-dist

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6.10.0
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/devil-fruit-backend:latest

      - name: Authenticate Docker with Google Cloud
        run: gcloud auth configure-docker

      - name: Add user to docker group
        run: |
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} \
            --zone ${{ secrets.GCP_INSTANCE_ZONE }} \
            --command "sudo usermod -aG docker $USER && newgrp docker"

      - name: Create directory on GCP Compute Engine
        run: |
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} \
            --zone ${{ secrets.GCP_INSTANCE_ZONE }} \
            --command "sudo mkdir -p /home/docker"

      - name: Copy docker-compose.yml to GCP Compute Engine
        run: |
          gcloud compute scp ./backend/docker-compose.yml ${{ secrets.GCP_INSTANCE_NAME }}:/home/docker/docker-compose.yml \
            --zone ${{ secrets.GCP_INSTANCE_ZONE }}

      - name: Pull Docker image on GCP Compute Engine
        run: |
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} \
            --zone ${{ secrets.GCP_INSTANCE_ZONE }} \
            --command "docker pull ghcr.io/${{ github.repository_owner }}/devil-fruit-backend:latest"

      - name: Run Docker Compose on GCP Compute Engine
        run: |
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} \
            --zone ${{ secrets.GCP_INSTANCE_ZONE }} \
            --command "cd /home/docker && docker compose up -d"
